# Generated by Django 4.2.1 on 2023-09-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_quantity'),
        ('customers', '0002_customer_name_alter_customer_email'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='robot_serial',
        ),
        migrations.AddField(
            model_name='order',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robot_order', to='robots.robot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='customers.customer'),
        ),
        migrations.CreateModel(
            name='WaitlistOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('is_backordered', models.BooleanField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_waitlist_order', to='customers.customer')),
            ],
        ),
    ]
